### ISSUE TITLE
VisualSampleEntry - not all child nodes are printed out

### ISSUE THREAD

**Issue by nonab** [baumerdev/mp4php#1]
Output from $mp4php->info()

                            === VisualSampleEntry (encv, 1324:237) ===
                            width: 1920
                            height: 1080
                            horizontalResolution: 
                                72

                            verticalResolution: 
                                72

                            frameCount: 1
                            compressorName: Elemental H.264                
                            depth: 24
                            pixelAspectRatio: 
                            esDescriptor: 
                            dataReferenceIndex: 1
                            children (2):

                                === Mp4php\Box\Box (avcC, 1410:71) ===
                                /== Mp4php\Box\Box (avcC, 1410:71) ===

                                === Mp4php\Box\Box (sinf, 1481:80) ===
                                /== Mp4php\Box\Box (sinf, 1481:80) ===
                            /== VisualSampleEntry (encv, 1324:237) ===

mp4dump output:

            [encv] size=8+229
              data_reference_index = 1
              width = 1920
              height = 1080
              compressor = Elemental H.264
              [avcC] size=8+63
                Configuration Version = 1
                Profile = High
                Profile Compatibility = 0
                Level = 40
                NALU Length Size = 4
                Sequence Parameter = [27 64 00 28 ac 72 10 07 80 22 7e 5c 05 a8 08 08 0a 00 00 03 00 02 00 00 03 00 65 c0 00 00 20 ce 60 00 06 26 b5 de f7 01 f0 88 45 12]
                Picture Parameter = [28 fb af 2c]
              [sinf] size=8+72
                [frma] size=8+4
                  original_format = avc1
                [schm] size=12+8
                  scheme_type = cenc
                  scheme_version = 65536
                [schi] size=8+32
                  [tenc] size=12+20
                    default_isProtected = 1
                    default_Per_Sample_IV_Size = 8
                    default_KID = [2f b6 8f c4 bd 45 4f cd ae e2 73 58 a6 8d 5d 18]

As you can see your code prints out 'sinf' without any children while it have 3 (frma, schm, schi), and one of them (schi) have 1 child (tenc)

Mp4 file used:
https://user-images.githubusercontent.com/1456315/111051281-36697e00-8452-11eb-9fec-a2cde63960d4.mp4

**Comment by baumerdev** [comment]
There are so many ISO box types in quite a few (sub)standards that I implemented only the ones I came across so far. The following boxes are now available:

avcC -> AVCConfiguration (it parses even a little bit more than mp4dump like chroma/luma)
sinf -> ProtectionSchemeInfo
frma -> OriginalFormat
schm -> SchemeType (it parses major.minor version "1.0" instead of mp4dump's int 65536)
schi -> SchemeInformation
tenc -> TrackEncryption

With those additions, the $mp4php->info() for your example file should look like this:

```
=== VisualSampleEntry (encv, 1324:237) ===
width: 1920
height: 1080
horizontalResolution:
    72

verticalResolution:
    72

frameCount: 1
compressorName: Elemental H.264
depth: 24
pixelAspectRatio:
esDescriptor:
dataReferenceIndex: 1
children (2):

    === AVCConfiguration (avcC, 1410:71) ===
    configurationVersion: 1
    profileIndication: High
    profileCompatibility: 0
    levelIndication: 4.0
    nalUnitLength: 4
    sequenceParamSets:
        0: [27 64 00 28 ac 72 10 07 80 22 7e 5c 05 a8 08 08 0a 00 00 03 00 02 00 00 03 00 65 c0 00 00 20 ce 60 00 06 26 b5 de f7 01 f0 88 45 12]

    pictureParamSets:
        0: [28 fb af 2c]

    chromaFormat: YUV 4:2:0
    bitDepthLuma: 8
    bitDepthChroma: 8
    sequenceParamSetsExt:

    /== AVCConfiguration (avcC, 1410:71) ===

    === ProtectionSchemeInfo (sinf, 1481:80) ===
    originalFormat:

        === OriginalFormat (frma, 1489:12) ===
        originalFormat: avc1
        /== OriginalFormat (frma, 1489:12) ===

    schemeType:

        === SchemeType (schm, 1501:20) ===
        schemeType: cenc
        schemeVersion: 1.0
        schemeUri:
        version: 0
        flags: 0
        /== SchemeType (schm, 1501:20) ===

    schemeInfo:

        === SchemeInformation (schi, 1521:40) ===
        children (1):

            === TrackEncryption (tenc, 1529:32) ===
            defaultIsEncrypted: (bool)true
            defaultIVSize: 8
            defaultKID: [2f b6 8f c4 bd 45 4f cd ae e2 73 58 a6 8d 5d 18]
            version: 0
            flags: 0
            /== TrackEncryption (tenc, 1529:32) ===
        /== SchemeInformation (schi, 1521:40) ===

    /== ProtectionSchemeInfo (sinf, 1481:80) ===
/== VisualSampleEntry (encv, 1324:237) ===
```
